name = "tworkz-vol8"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-09-05"
compatibility_flags = ["nodejs_compat"]
preview_urls = true

[assets]
binding = "ASSETS"
directory = "dist"

[[r2_buckets]]
binding = 'R2'
bucket_name = 'tech-nation-records'